name: notepad
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  app_popup_menu: ^1.0.0
  ndialog: ^4.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  calendar_date_picker2: ^0.5.3
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  lite_rolling_switch: ^1.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

